version: '3.4'

services:
  fp_l:
    container_name: fp_l-api
    image: ${DOCKER_REGISTRY-}fpl
    build:
      context: .
      dockerfile: FP_L/Dockerfile
    ports: 
      - 8185:8080
    networks:
    - fp_l-net

networks:
  fp_l-net:


